'use client';

import { useEffect, useState } from 'react';
import { Button, Form, Input, Modal, Select, Tag, message } from 'antd';
import { DeleteOutlined, EditOutlined, PlusOutlined, StarOutlined } from '@ant-design/icons';
import { useLocale } from 'next-intl';
import apiClient from '@/lib/api';
import type { ChileCommune, ChileRegion, UserAddress } from '@/types';

export default function AddressBookManager() {
  const locale = useLocale(); const es = locale !== 'en';
  const [rows, setRows] = useState<UserAddress[]>([]); const [regions, setRegions] = useState<ChileRegion[]>([]); const [communes, setCommunes] = useState<ChileCommune[]>([]);
  const [editing, setEditing] = useState<UserAddress | null | undefined>(undefined); const [form] = Form.useForm(); const regionID = Form.useWatch('region_id', form);
  const load = async () => { const [addressResponse, regionResponse] = await Promise.all([apiClient.get('/me/addresses'), apiClient.get('/locations/regions')]); setRows(addressResponse.data.data || []); setRegions(regionResponse.data.data || []); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!regionID) { setCommunes([]); return; } void apiClient.get(`/locations/regions/${regionID}/communes`).then((response) => setCommunes(response.data.data || [])); }, [regionID]);
  const open = (row?: UserAddress) => { setEditing(row || null); form.setFieldsValue(row || { is_default: rows.length === 0 }); };
  const save = async () => { const values = await form.validateFields(); if (editing?.id) await apiClient.put(`/me/addresses/${editing.id}`, values); else await apiClient.post('/me/addresses', values); setEditing(undefined); form.resetFields(); await load(); message.success(es ? 'Dirección guardada' : 'Address saved'); };
  const remove = async (id: number) => { await apiClient.delete(`/me/addresses/${id}`); await load(); };
  const makeDefault = async (id: number) => { await apiClient.post(`/me/addresses/${id}/default`); await load(); };
  return <section className="mt-12 border-t border-[var(--sf-line)] pt-8"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-black">{es ? 'Mis direcciones' : 'My addresses'}</h2><p className="mt-1 text-sm text-[var(--sf-muted)]">{es ? 'Solo tú puedes ver y administrar estas direcciones.' : 'Only you can view and manage these addresses.'}</p></div><Button icon={<PlusOutlined />} onClick={() => open()}>{es ? 'Agregar' : 'Add'}</Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{rows.map((row) => <article key={row.id} className="rounded-[16px] border border-[var(--sf-line)] p-4"><div className="flex items-start justify-between"><strong>{row.label || row.recipient}</strong>{row.is_default && <Tag color="blue">{es ? 'Predeterminada' : 'Default'}</Tag>}</div><p className="mt-2 text-sm">{row.street} {row.street_number}{row.complement ? `, ${row.complement}` : ''}</p><p className="text-sm text-[var(--sf-muted)]">{row.commune?.name} · {row.region?.name}</p><div className="mt-4 flex flex-wrap gap-2"><Button size="small" icon={<EditOutlined />} onClick={() => open(row)}>{es ? 'Editar' : 'Edit'}</Button>{!row.is_default && <Button size="small" icon={<StarOutlined />} onClick={() => void makeDefault(row.id)}>{es ? 'Predeterminada' : 'Default'}</Button>}<Button danger size="small" icon={<DeleteOutlined />} onClick={() => void remove(row.id)}>{es ? 'Eliminar' : 'Delete'}</Button></div></article>)}</div>
    <Modal open={editing !== undefined} title={editing?.id ? (es ? 'Editar dirección' : 'Edit address') : (es ? 'Nueva dirección' : 'New address')} onCancel={() => setEditing(undefined)} onOk={() => void save()} destroyOnHidden><Form form={form} layout="vertical"><div className="grid gap-x-3 sm:grid-cols-2"><Form.Item name="label" label={es ? 'Etiqueta' : 'Label'}><Input /></Form.Item><Form.Item name="recipient" label={es ? 'Destinatario' : 'Recipient'} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="phone" label={es ? 'Teléfono' : 'Phone'} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="region_id" label="Región" rules={[{ required: true }]}><Select onChange={() => form.setFieldValue('commune_id', undefined)} options={regions.map((row) => ({ value: row.id, label: row.name }))} /></Form.Item><Form.Item name="commune_id" label="Comuna" rules={[{ required: true }]}><Select options={communes.map((row) => ({ value: row.id, label: row.name }))} /></Form.Item><Form.Item name="street" label={es ? 'Calle' : 'Street'} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="street_number" label={es ? 'Número' : 'Number'} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="complement" label={es ? 'Complemento' : 'Complement'}><Input /></Form.Item><Form.Item name="reference" label={es ? 'Referencia' : 'Reference'}><Input /></Form.Item></div></Form></Modal>
  </section>;
}
