'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Divider, InputNumber, message, Popconfirm, Spin, Tag, Typography } from 'antd';
import { ArrowLeftOutlined, DeleteOutlined, MinusOutlined, PlusOutlined, ShoppingCartOutlined, WarningOutlined } from '@ant-design/icons';
import Link from 'next/link';
import { useLocale, useTranslations } from 'next-intl';
import ImageFallback from '@/components/ImageFallback';
import EmptyState from '@/components/EmptyState';
import { useAuthStore } from '@/store/useAuthStore';
import { useCartStore } from '@/store/useCartStore';
import type { CartItem } from '@/types';

const { Title, Text } = Typography;
export default function CartPage() {
  const t = useTranslations(); const locale = useLocale(); const cart = useCartStore(); const { isAuthenticated } = useAuthStore();
  const [initialLoading, setInitialLoading] = useState(true); const [updating, setUpdating] = useState<Set<number>>(new Set());
  useEffect(() => { (async () => { if (isAuthenticated) await cart.fetchCart(); setInitialLoading(false); })(); // cart is a stable Zustand store facade
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cart.fetchCart, isAuthenticated]);
  const warnings = useMemo(() => new Map(cart.items.filter((item) => item.sku && item.quantity > item.sku.inventory).map((item) => [item.sku_id, t('cart.stockLimit', { count: item.sku!.inventory })])), [cart.items, t]);
  const money = (amount: number) => new Intl.NumberFormat(locale, { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(amount);
  const change = useCallback(async (skuId: number, quantity: number | null) => { const item = cart.items.find((value) => value.sku_id === skuId); if (!quantity || quantity < 1 || !item) return; if (item.sku && quantity > item.sku.inventory) { message.warning(t('cart.stockLimit', { count: item.sku.inventory })); return; } setUpdating((old) => new Set(old).add(skuId)); try { await cart.updateQuantity(skuId, quantity); } catch { message.error(t('cart.updateFailed')); } finally { setUpdating((old) => { const next = new Set(old); next.delete(skuId); return next; }); } }, [cart, t]);
  const remove = async (skuId: number) => { try { await cart.removeItem(skuId); message.success(t('cart.removed')); } catch { message.error(t('cart.removeFailed')); } };
  const clear = async () => { try { await cart.clearCart(); message.success(t('cart.clearCartSuccess')); } catch { message.error(t('cart.clearFailed')); } };
  if (initialLoading || cart.isLoading) return <main className="store-container flex items-center justify-center min-h-[400px]"><Spin size="large" /></main>;
  if (!cart.items.length) return <main className="store-container"><Title level={2}><ShoppingCartOutlined /> {t('cart.title')}</Title><EmptyState title={t('cart.emptyTitle')} description={t('cart.emptyDesc')} actionLabel={t('cart.shopNow')} actionHref={`/${locale}/products`} /></main>;
  return <main className="store-container space-y-6" id="main-content"><div className="flex flex-col sm:flex-row sm:justify-between gap-4"><Title level={2} className="!mb-0"><ShoppingCartOutlined /> {t('cart.title')} <Tag>{t('cart.itemQuantity', { count: cart.totalItems })}</Tag></Title><Popconfirm title={t('cart.confirmClear')} onConfirm={clear} okText={t('common.confirm')} cancelText={t('common.cancel')}><Button danger type="text">{t('cart.clearCart')}</Button></Popconfirm></div>{warnings.size > 0 && <div className="bg-warning/5 border border-warning/20 rounded-xl p-4 flex gap-3"><WarningOutlined className="text-warning" /><div><b>{t('cart.inventoryWarning')}</b><p className="text-sm">{t('cart.inventoryInsufficient')}</p></div></div>}<div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-3">{cart.items.map((item) => <CartRow key={item.sku_id} item={item} warning={warnings.get(item.sku_id)} updating={updating.has(item.sku_id)} onChange={change} onRemove={remove} money={money} />)}</div><aside className="sticky top-24 h-fit rounded-xl border p-6 space-y-4"><h2 className="text-lg font-bold">{t('cart.orderSummary')}</h2><Divider /><div className="space-y-3"><div className="flex justify-between"><span>{t('cart.itemCount')}</span><span>{t('cart.itemQuantity', { count: cart.totalItems })}</span></div><div className="flex justify-between"><span>{t('cart.totalPrice')}</span><span>{money(cart.totalPrice)}</span></div><div className="flex justify-between"><span>{t('cart.shippingFee')}</span><span>{t('cart.shippingCalc')}</span></div></div><Divider /><div className="flex justify-between font-bold text-lg"><span>{t('cart.total')}</span><span>{money(cart.totalPrice)}</span></div><Link href={`/${locale}/checkout`}><Button type="primary" block size="large" disabled={warnings.size > 0}>{t('cart.proceedToCheckout')}</Button></Link>{warnings.size > 0 && <Text type="warning">{t('cart.handleInventory')}</Text>}<Link href={`/${locale}/products`}><Button block icon={<ArrowLeftOutlined />}>{t('cart.continueShopping')}</Button></Link></aside></div></main>;
}
function CartRow({ item, warning, updating, onChange, onRemove, money }: { item: CartItem; warning?: string; updating: boolean; onChange: (id: number, quantity: number | null) => void; onRemove: (id: number) => void; money: (value: number) => string }) {
  const t = useTranslations(); const name = item.sku?.product?.name || item.sku_name || item.sku_code || `SKU #${item.sku_id}`; const image = item.image_url || item.sku?.image_url; const max = item.max_quantity ?? item.sku?.inventory ?? 99; const soldOut = item.available === false || max <= 0;
  return <div className="store-card p-4 flex gap-4 items-center"><div className="relative w-16 h-16 shrink-0">{image ? <ImageFallback src={image} alt={name} fill className="object-cover rounded-lg" /> : <ShoppingCartOutlined />}</div><div className="flex-1 min-w-0"><b className="block truncate">{name}</b>{soldOut && <Tag color="error">{t('common.soldOut')}</Tag>}{warning && <p className="text-warning text-xs mt-1">{warning}</p>}<span className="text-sm text-muted">{money(item.unit_price)}</span></div><div className="flex items-center border rounded"><Button type="text" icon={<MinusOutlined />} disabled={item.quantity <= 1 || soldOut || updating} aria-label={t('cart.quantityDecrease')} onClick={() => onChange(item.sku_id, item.quantity - 1)} /><InputNumber controls={false} min={1} max={max} value={item.quantity} disabled={soldOut || updating} aria-label={t('cart.quantity')} onChange={(value) => onChange(item.sku_id, value)} className="w-12" /><Button type="text" icon={<PlusOutlined />} disabled={item.quantity >= max || soldOut || updating} aria-label={t('cart.quantityIncrease')} onClick={() => onChange(item.sku_id, item.quantity + 1)} /></div><b className="w-24 text-right">{money(item.subtotal)}</b><Popconfirm title={t('cart.confirmRemove')} onConfirm={() => onRemove(item.sku_id)} okText={t('common.confirm')} cancelText={t('common.cancel')}><Button type="text" danger icon={<DeleteOutlined />} aria-label={t('cart.remove')} /></Popconfirm></div>;
}
