import LegalDocument from '@/components/legal/LegalDocument';
import { supplierProfile } from '@/lib/legal/supplier';
import Link from 'next/link';

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; const es = locale !== 'en';
  return <LegalDocument locale={locale} title={es ? 'Política de privacidad' : 'Privacy policy'}>
    <section><h2 className="text-xl font-black">{es ? 'Responsable y contacto' : 'Controller and contact'}</h2><p>{es ? `${supplierProfile.legalName}, RUT ${supplierProfile.rut}, es responsable del tratamiento descrito. Consultas: ${supplierProfile.supportEmail}.` : `${supplierProfile.legalName}, RUT ${supplierProfile.rut}, is responsible for the processing described here. Questions: ${supplierProfile.supportEmail}.`}</p></section>
    <section><h2 className="text-xl font-black">{es ? 'Datos y finalidades' : 'Data and purposes'}</h2><p>{es ? 'Podemos tratar nombre, correo, teléfono, dirección de despacho, RUT solo cuando sea necesario para documentación tributaria, pedidos, pagos declarados, soporte, seguridad y datos técnicos estrictamente necesarios. Se usan para ejecutar pedidos, despachar, documentar ventas, atender posventa, prevenir abuso y operar el sitio.' : 'We may process name, email, phone, shipping address, RUT only where needed for tax documents, orders, declared payments, support, security, and strictly necessary technical data. These are used to fulfil orders, deliver, document sales, provide after-sales support, prevent abuse, and operate the site.'}</p></section>
    <section><h2 className="text-xl font-black">{es ? 'Proveedores y transferencias' : 'Providers and transfers'}</h2><p>{es ? 'Solo se compartirán datos mínimos con servicios efectivamente habilitados de alojamiento, correo transaccional, pago y logística. Stripe, PayPal, publicidad y otros proveedores no se declararán como activos mientras no estén habilitados. El inventario definitivo de proveedores, países y plazos de conservación queda sujeto a revisión operativa y jurídica antes de publicar una versión aprobada.' : 'Only minimum data will be shared with hosting, transactional email, payment, and logistics services actually enabled. Stripe, PayPal, advertising, and other providers will not be presented as active while disabled. The final provider, country, and retention inventory remains subject to operational and legal review before an approved version is published.'}</p></section>
    <section><h2 className="text-xl font-black">{es ? 'Derechos' : 'Rights'}</h2><p>{es ? `Puedes solicitar acceso, corrección, eliminación, oposición, bloqueo, portabilidad o retiro de marketing escribiendo a ${supplierProfile.supportEmail}. Antes de entregar o modificar datos verificaremos la identidad de manera proporcional. Las obligaciones legales de conservación pueden requerir restringir datos en vez de eliminarlos.` : `You may request access, correction, deletion, objection, blocking, portability, or marketing withdrawal by writing to ${supplierProfile.supportEmail}. We will proportionately verify identity before disclosing or changing data. Legal retention duties may require restriction instead of deletion.`}</p><Link className="mt-4 inline-flex font-bold underline" href={`/${locale}/privacy-request`}>{es ? 'Enviar una solicitud de privacidad' : 'Submit a privacy request'}</Link></section>
  </LegalDocument>;
}
